### ISSUE TITLE
Wrong savestate FS path on SD2Vita + yamt

### ISSUE THREAD

**Issue by MERLev** [TheOfficialFloW/dejavu#1]
I am using SD2Vita paired with "yamt-vita" plugin.
SD2Vita is mounted as ux0, MemCard is mounted as uma0.

Expected behaviour: savestate is saved to ux0
Actual behaviour: savestate  is saved to uma0

**Comment by TheOfficialFloW** [comment]
That's expected. It is only able to write to Memory Card.
